"use client";

import { ThemeProvider } from '@mui/material'
import './globals.css'
import type { Metadata } from 'next'
import theme from '../components/theme';
import { Inter } from 'next/font/google'
import Header from '@/components/Header';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


const publicRoutesHeader = ["/about", "/inquiry"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();  // Get the current route
  const isHeader = !publicRoutesHeader.includes(pathname);


  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider theme={theme}>
        {isHeader && <Header />}
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
